import { Link,useNavigate,useRouterState } from "@tanstack/react-router";
import { BarChart3,BookOpenCheck,FileSearch,Files,HelpCircle,LogOut,Menu,Scale,Settings,ShieldCheck,Waypoints } from "lucide-react";
import { Brand } from "@/components/brand";
import { Button } from "@/components/ui/button";
import { Sheet,SheetContent,SheetTrigger,SheetTitle } from "@/components/ui/sheet";
import { useAuth } from "@/contexts/auth-context";
const nav=[{to:"/dashboard",label:"Overview",icon:BarChart3},{to:"/analyze",label:"Analyze",icon:FileSearch},{to:"/documents",label:"Documents",icon:Files},{to:"/standards",label:"Standards",icon:Waypoints},{to:"/compliance",label:"Compliance",icon:ShieldCheck},{to:"/changes",label:"Change Impact",icon:Scale}] as const;
function SidebarContent(){const path=useRouterState({select:(state)=>state.location.pathname});const {profile,signOut}=useAuth();const navigate=useNavigate();return <div className="flex h-full flex-col"><Brand/><nav className="mt-10 grid gap-1" aria-label="Workspace">{nav.map(({to,label,icon:Icon})=><Link key={to} to={to} className={path===to||path.startsWith(`${to}/`)?"side-link side-link-active":"side-link"}><Icon/><span>{label}</span></Link>)}</nav><div className="mt-auto grid gap-1 border-t border-border pt-4"><a href="mailto:support@standardos.in" className="side-link"><HelpCircle/><span>Help</span></a><Link to="/settings" className={path==="/settings"?"side-link side-link-active":"side-link"}><Settings/><span>Settings</span></Link><div className="mt-3 flex min-w-0 items-center gap-3 px-2 py-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">{profile?.full_name.split(" ").map((word)=>word[0]).slice(0,2).join("")||"SO"}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-primary">{profile?.full_name??"Workspace user"}</p><p className="truncate text-xs text-muted-foreground">{profile?.organization??"STANDARDOS"}</p></div><Button size="icon" variant="ghost" aria-label="Log out" title="Log out" onClick={async()=>{await signOut();void navigate({to:"/login",replace:true})}}><LogOut/></Button></div></div></div>}
export function AppSidebar(){return <><aside className="fixed inset-y-0 left-0 z-30 hidden w-64 border-r border-border bg-sidebar/80 p-5 backdrop-blur-xl lg:block"><SidebarContent/></aside><div className="fixed inset-x-0 top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/85 px-4 backdrop-blur-xl lg:hidden"><Brand/><Sheet><SheetTrigger asChild><Button variant="ghost" size="icon" aria-label="Open workspace navigation"><Menu/></Button></SheetTrigger><SheetContent side="left" className="w-[84%] p-5"><SheetTitle className="sr-only">Workspace navigation</SheetTitle><SidebarContent/></SheetContent></Sheet></div></>}
